name: landscape-client-core
title: Landscape Client for Ubuntu Core
base: core24
version: 26.04
summary: Landscape client for Ubuntu Core devices
description: |
  Manages Ubuntu Core devices with Canonical Landscape.
  Provides system monitoring and remote management.
confinement: strict
grade: stable
contact: https://www.canonical.com/contact-us
license: GPL-3.0+
donation: https://www.canonical.com/donate
issues: https://www.canonical.com/issue
source-code: https://www.github.com/canonical/
website: https://www.canonical.com

apps:
  landscape-client-core:
    command: bin/landscape-client-core
    daemon: simple
    restart-condition: on-failure
    environment:
      GOGC: "50"
    plugs:
      - network
      - snapd-control
      - system-observe
      - hardware-observe
      - shutdown
      - log-observe
      - mount-observe

  config:
    command: bin/landscape-client-core-config
    plugs:
      - network

hooks:
  install: {}
  post-refresh: {}
  configure:
    plugs:
      - network

parts:
  landscape-client-core:
    plugin: go
    source: .
    build-snaps:
      - go/1.22/stable
    stage-packages:
      - lshw
      - curl
    override-build: |
      go build -ldflags="-s -w" -trimpath -o "$CRAFT_PART_INSTALL/bin/" ./cmd/landscape-client-core/ ./cmd/landscape-client-core-config/
